### ISSUE TITLE
Trying to login user labuser username password

### ISSUE THREAD

**Issue by dsouzabash** [Adobe-Marketing-Cloud/analytics-realtime-dashboard-example#22]
Hello, 

According to instructions in Lesson 1, I am trying to follow these instructions

> In your browser go to https://marketing.adobe.com/developer/api-explorer
> 
> Enter the following credentials
> 
> API Username: labuser:Real Time Dashboard Lab
> Secret: 75d03af19787f81a6f5016c885bc3541
> 

 But when I click on the get Response button the request fails. 

{
	"error":"Bad Request",
	"error_description":"Unable to validate authentication.",
	"error_uri":null
}

When I go under My account information to login using my own company credentials, I don't see an option to find out the secret key for my account

![image](https://cloud.githubusercontent.com/assets/7214045/12762146/a9fbf0f2-c9a2-11e5-8c70-46d11876818a.png)

Any help would be appreciated. 

Thanks.

Ashley DSouza.

**Comment by dsouzabash** [comment]
Never mind, I got my omniture admin to add me to a group which got me access to the secret key.

**Comment by garyr** [comment]
Glad you found it, thanks for reaching out! We'll be offering this lab again at Summit 2016 in Las Vegas if you are able to attend
