### ISSUE TITLE
Problem with amp-analytics and adobe's list variables

### ISSUE THREAD

**Issue by fdosruiz** [Adobe-Marketing-Cloud/analytics-realtime-dashboard-example#35]
we're having problems to collect list variables from Adobe Omniture sent through the amp-analytics tag.
All parameters defined into the key "requests" in amp-analytics is collected properly by Adobe, except list variables. In the request the variables are being sent with the correct format.

![query](https://cloud.githubusercontent.com/assets/4465438/21847925/b8dd5280-d7fe-11e6-88fa-5b673a56a1a8.png)

The code used into request key:
`			"requests": {
				"base": "https://${trackingServer}/b/ss/${accounts}/1/AMP-0.1/s${random}",
				"pageView": "${base}?AQB=1&vid=CLIENT_ID(amp_id)&pageName=${canonicalPath}&v3=D=pageName&c6=${documentReferrer}&v63=${documentReferrer}&c5=${canonicalUrl}&v10=${canonicalUrl}&c11=${ampdocUrl}&v11=D=c11&c12=${ampdocUrl}&c17=Multi AMP&v17=Multi AMP&c18=prisa&v18=D=c18&c19=el pais&v19=D=c19&c20=${canonicalHost}&v20=D=c20&c39=${title}&v39=D=c39&c45=${title}&v45=D=c45&c57=D=User-Agent&v57=D=User-Agent&j=amp&v0=${queryParam(0p19G)}&AQE=1&L2=23380%3B32455%3B38911%3B24796%3B40110%3B76591%3B68464%3B76590%3B75097%3B30342%3B75441%3B23903%3B37231%3B46997%3B25091%3B146640%3B16438%3B9757%3B75914%3B15145&L3=80945",
				"share": "${base}?AQB=1&vid=CLIENT_ID(amp_id)&pageName=${canonicalPath}&v3=D=pageName&c6=${documentReferrer}&v63=${documentReferrer}&c5=${canonicalUrl}&v10=${canonicalUrl}&c11=${ampdocUrl}&v11=D=c11&c12=${ampdocUrl}&c17=Multi AMP&v17=Multi AMP&c18=prisa&v18=D=c18&c19=el pais&v19=D=c19&c20=${canonicalHost}&v20=D=c20&c39=${title}&v39=D=c39&c45=${title}&v45=D=c45&c57=D=User-Agent&v57=D=User-Agent&j=amp&pe=lnk_o&v69=${eVar69}&events=${events}&AQE=1&L2=23380%3B32455%3B38911%3B24796%3B40110%3B76591%3B68464%3B76590%3B75097%3B30342%3B75441%3B23903%3B37231%3B46997%3B25091%3B146640%3B16438%3B9757%3B75914%3B15145&L3=80945"
			},`

We have this problem only with AMP requests. The web version requests have this parameter with the same format, but in this case works properly.

Thanks
Francisco.

**Comment by garyr** [comment]
Francisco. Sorry for the delayed response, we don't often check or respond to issue requests on this repo. In the future, please contact Adobe Customer Support for assistance
